### PR TITLE
Add Nim Telegram

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Add the official Nim Telegram link.

### CODE REVIEW

**Comment by vpashkov** [comment]
Awesome. Thank you.

**Comment by data-man** [comment]
@VPashkov 
Revert this PR please. Until the situation becomes clearer.
This channel  isn't mentioned in https://nim-lang.org/community.html

@juancarlospaco 
Are you a member of the Nim-Lang organization?

**Comment by juancarlospaco** [comment]
The Telegram neither is listed on https://nim-lang.org/community.html , 
but we are there, also Dominik and others.

You can instead try to contribute an update to https://nim-lang.org/community.html
:confused:

**Comment by data-man** [comment]
@juancarlospaco

My apologies, everything cleared up!

**Comment by dom96** [comment]
Yeah, please add it to our website too.

**Pull request merged**
