### PR TITLE
Update a link for Nim packages

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by dom96** [comment]
I would add that as a separate item, both are equally useful IMO

**Comment by vpashkov** [comment]
@dom96, agree.
@narimiran, can you please add [nimble.directory](https://nimble.directory/) as a separate item, without removing "[Nim packages](https://github.com/nim-lang/packages)" entry?

**Comment by narimiran** [comment]
Done.

**Comment by vpashkov** [comment]
Thank you!

**Pull request merged**
